### ISSUE TITLE
running through Gradle

### ISSUE THREAD

**Issue by tedder** [beckje01/grails-code-coverage#23]
I'm using Gradle 1.12 and Grails 2.3.6. I've included the coverage plugin:

```
dependencies {
  test "org.grails.plugins:code-coverage:1.2.7"
}
```

I then make sure to pass the `-coverage` argument:

```
project.tasks.'grails-test-app' {
  args = '-coverage'
}
```

When I run `./gradlew clean test` or `./gradlew clean grails-test-app` I don't see the expected "Instrumenting classes for coverage" output.

I also tried turning forking off, based on #11, with `./gradlew clean grails-test-app -Pgrails.project.fork.test=false`. No dice.

I also added a dependency to gradle:

```
buildscript {
  dependencies {
        classpath "org.grails.plugins:code-coverage:1.2.7"
  }
}
```

Again, it didn't help. So, how does grails-code-coverage integrate with Gradle?

**Comment by beckje01** [comment]
I have not tried to use this plugin with gradle based grails builds. I would think you could use the gradle plugins for code coverage and have an easier way to to work with the plugins... but I'm not sure. 

If you have a public repo with the grails built by gradle I might be able to take a look soon.

**Comment by beckje01** [comment]
So if you need anything more on this contact me on twitter.
