### ISSUE TITLE
Grails 2.3.9 ClassNotFoundException PackageData

### ISSUE THREAD

**Issue by michaelnico** [beckje01/grails-code-coverage#26]
When I updated my grails version to 2.3.9 from 2.3.7 I experienced this issue:

```
Error Cobertura: Error reading from object stream.
java.lang.ClassNotFoundException: net.sourceforge.cobertura.coveragedata.PackageData

Cobertura: Coverage data file /home/user/cobertura.ser either does not exist or is not readable.  Creating a new data file.
```

**Comment by Alotor** [comment]
I had the same issue and deactivating the fork mode for "test" is working. 

Maybe something about the forked mode changed on Grails 2.3.9?

**Comment by beckje01** [comment]
I am testing the latest snapshot with 2.3.9 now and I'll let you know soon.

**Comment by mukulashokjoshi** [comment]
Found the same issue in version 2.4 RC2 as well

**Comment by mukulashokjoshi** [comment]
And it worked (in 2.4 RC2) by switching off the "forked" mode for test. Thanks Alotor.

**Comment by beckje01** [comment]
So we do not support forked mode at this time for any version.
