### ISSUE TITLE
Unable to find plugin

### ISSUE THREAD

**Issue by monyag** [beckje01/grails-code-coverage#47]
Where I can find this plugin?

Could not find artifact org.grails.plugins:code-coverage:jar:2.0.3-3 in grailsCentral (http://repo.grails.org/grails/plugins)

Also I tried to find plugin in
repositories {
      ...
      mavenRepo "http://mojo.codehaus.org"
}

Resolve error obtaining dependencies: Could not transfer artifact org.grails.plugins:code-coverage:jar:2.0.3-3 from/to mojo_codehaus_org (http://mojo.codehaus.org): Checksum validation failed

**Comment by beckje01** [comment]
Not sure it seems to be in http://repo.grails.org/grails/plugins/org/grails/plugins/code-coverage/2.0.3-3/ correctly. 

This only works for grails 2 what are you using?

**Comment by monyag** [comment]
I worked two days with locally-builded plugin, but now repo works fine. I think, that is not the issue of the plugin. Grails 2.3.11.

**Comment by beckje01** [comment]
Great must have been some wires crossed some where in the internet
