### ISSUE TITLE
Grails.org plugin listing shows misleading usage

### ISSUE THREAD

**Issue by kenhtanaka** [beckje01/grails-code-coverage#5]
Looking at http://grails.org/plugins/search?q=code+coverage
shows an incorrect entry for BuildConfig.groovy

Dependency :
compile ":code-coverage:1.2.6"

but if one clicks on the "Read more" ( http://grails.org/plugin/code-coverage ) link, the next page shows the correct

Dependency :
test ":code-coverage:1.2.6"

**Comment by beckje01** [comment]
Interesting looks like a bug in the plugin portal. I'll send a message to the dev list.

**Comment by beckje01** [comment]
Sorry its an issue in the plugin portal I can't fix from my end.
