### ISSUE TITLE
Please publish a version of the plugin compatible with grails 3.x

### ISSUE THREAD

**Issue by ddelponte** [beckje01/grails-code-coverage#51]
Are their plans to release a new version of this plugin which supports grails 3.x?

**Comment by beckje01** [comment]
There is no need for grails 3.x you can use gradle tools directly in that case see:

My old post:
http://beckje01.com/blog/2015/07/12/grails-3-and-jacoco/

A recent post with lost of details:
http://mariogarcia.github.io/blog/blog/2017/04/grails_coverage.html

Clover Info:
http://guides.grails.org/grails-code-coverage/guide/index.html

**Comment by beckje01** [comment]
But if you think this info would be good to add to the readme I would love a PR with some wordsmithing!
