### ISSUE TITLE
ClassNotFoundException (Jenkins)

### ISSUE THREAD

**Issue by davidadale** [beckje01/grails-code-coverage#6]
I am getting this error when I try to build using Jenkins.

grails "test-app :unit -coverage -xml" "test war"

Fails trying to build the war

Error [22;39mError loading plugin manager: java.lang.ClassNotFoundException: CodeCoverageGrailsPlugin (Use --stacktrace to see the full trace)
Build step 'Build With Grails' marked build as failure
Skipping Cobertura coverage report as build was not UNSTABLE or better ...
Finished: FAILURE

**Comment by beckje01** [comment]
What version of grails are you using?

**Comment by davidadale** [comment]
Sorry misread the question. I am using Grails 2.2.3

This is what I have in my BuildConfig.groovy

test ":code-coverage:1.2.6"

If I change it to 

compile ":code-coverage:1.2.6"

the build completes but the app fails to start complaining about the ClassNotFound same thing.

 **Let me try to remove the post processing -nopost**

**Comment by davidadale** [comment]
Changing it to -nopost didn't help

**Comment by beckje01** [comment]
ok I will try and reproduce thanks for the details

**Comment by davidadale** [comment]
Hey I have a fix on this.

Instead of using 
test ":code-coverage:1.2.6"

use 

build ":code-coverage:1.2.6"

**That Works!!**

Thanks for your quick response on this.

**Comment by beckje01** [comment]
Interesting do you have to build the war as test? I think that is what is causing it.

**Comment by davidadale** [comment]
Yah, in our case we are using the test settings as the settings for our
test environment. You're probably right about that but it's working now.
