### ISSUE TITLE
Cobertura cannot find the source for a Quartz job

### ISSUE THREAD

**Issue by zoran119** [beckje01/grails-code-coverage#7]
Not sure it if it a bug but I get the following message when trying to see the coverage report for a Quartz job: `Unable to locate example/MyJob.groovy. Have you specified the source directory?`

**Comment by mjhugo** [comment]
Have you tried specifying the jobs directory in sourceInclusions (see
below, replace 'realms' with 'jobs')

In addition, you can add directories to the default list for source files
to include in the coverage reports. For example, if you're using the
Jsecurity plugin and want to see the source for files in the 'realms'
directory in the reports, add the following to your BuildConfig.groovy:

coverage {
     // list of directories to search for source to include in coverage reports
     sourceInclusions = ['grails-app/realms']
}

On Wed, Sep 11, 2013 at 12:25 AM, Zoran Stojakovic <notifications@github.com

> wrote:
> 
> Not sure it if it a bug but I get the following message when trying to see
> the coverage report for a Quartz job: Unable to locate
> au/edu/uow/its/lmsm/SiteProvisioningWithNoCloneJob.groovy. Have you
> specified the source directory?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/beckje01/grails-code-coverage/issues/7
> .

## 

Mike Hugo
Senior Software Engineer
Entagen, LLC
612-669-8856
mike@entagen.com

**Comment by beckje01** [comment]
@zoran119 Did Mike's suggestion fix your problem?

**Comment by zoran119** [comment]
I could not fix the problem on a project at work despite adding `sourceInclusions`, yet trying `sourceInclusions` on a dummy new project works fine. I'll have another go when I go to work on Monday and let you guys know (I must have an error in my config somewhere...).

Thanks for quick response!

**Comment by zoran119** [comment]
Just tried it again, it found the sources. Thanks for your help.
