### ISSUE TITLE
Upgrade to Cobertura 2.0.3

### ISSUE THREAD

**Issue by beckje01** [beckje01/grails-code-coverage#9]
Upgrade to cobertura 2.0.3

https://github.com/cobertura/cobertura

**Comment by ziftytodd** [comment]
I tried working on this a bit myself, but once I was able to resolve some dependency issues, it appears that no classes were instrumented correctly, or the data wasn't being saved properly. Have you had any luck in getting 2.0.3 to work in your efforts?

**Comment by beckje01** [comment]
I ran into a cobetura bug with incompatible class change so I'm holding off for now.

**Comment by beckje01** [comment]
Here is where I started https://github.com/beckje01/grails-code-coverage/tree/coberturaUpgrade

**Comment by mihaildemidoff** [comment]
It's not a cobertura bug. We have incompatibility between bundled asm library(3.3.1 in grails) and asm used in cobertura 2.0.X(asm 4.X). We can only wait for version upgrading in grails.

**Comment by beckje01** [comment]
Agreed thanks for the input.

**Comment by nikolajbrinch** [comment]
I've fixed this issue in the pull request, by booting the instrumentation in a new JVM, where I have removed asm 3 from the classpath.

Check out my pull request.

Happy testing :-)

**Comment by beckje01** [comment]
Fixed by @nikolajbrinch
